// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0PQssJU0htlH_dBpEAKr45Gbx6rot_8I',
    appId: '1:24515793584:web:1668afd43e64d64fb7e175',
    messagingSenderId: '24515793584',
    projectId: 'smarttracker-f9fc1',
    authDomain: 'smarttracker-f9fc1.firebaseapp.com',
    storageBucket: 'smarttracker-f9fc1.firebasestorage.app',
    measurementId: 'G-TZSYYRK7J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHYxoKzxvkFir_YBkpoJZNy-Nu3DkRUB4',
    appId: '1:24515793584:android:c5d33a9a89e75fc3b7e175',
    messagingSenderId: '24515793584',
    projectId: 'smarttracker-f9fc1',
    storageBucket: 'smarttracker-f9fc1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0PQssJU0htlH_dBpEAKr45Gbx6rot_8I',
    appId: '1:24515793584:web:655a5753235cfaa0b7e175',
    messagingSenderId: '24515793584',
    projectId: 'smarttracker-f9fc1',
    authDomain: 'smarttracker-f9fc1.firebaseapp.com',
    storageBucket: 'smarttracker-f9fc1.firebasestorage.app',
    measurementId: 'G-48KELXS1DC',
  );
}
