// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgpH1Pvk0eHH9_Y0bdmC2CtSV6o-AtVlM',
    appId: '1:327926247616:web:9ef838832332291cbb7d25',
    messagingSenderId: '327926247616',
    projectId: 'fooddelightapp-new',
    authDomain: 'fooddelightapp-new.firebaseapp.com',
    storageBucket: 'fooddelightapp-new.firebasestorage.app',
    measurementId: 'G-R3Q2M98PXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT0S1bztbyJ3nh9D9PWsZQ9qD5HqgwiXc',
    appId: '1:327926247616:android:653556bd63f3612ebb7d25',
    messagingSenderId: '327926247616',
    projectId: 'fooddelightapp-new',
    storageBucket: 'fooddelightapp-new.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgpH1Pvk0eHH9_Y0bdmC2CtSV6o-AtVlM',
    appId: '1:327926247616:web:5503e82b0c8c654cbb7d25',
    messagingSenderId: '327926247616',
    projectId: 'fooddelightapp-new',
    authDomain: 'fooddelightapp-new.firebaseapp.com',
    storageBucket: 'fooddelightapp-new.firebasestorage.app',
    measurementId: 'G-KKP9GF9VR6',
  );

}